# Generated by Django 3.2.3 on 2021-09-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210928_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='start_date',
            new_name='activated_on',
        ),
    ]
