# Generated by Django 3.2.3 on 2021-10-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20211002_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
    ]
