# Generated by Django 3.2.3 on 2021-10-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20211006_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptype',
            old_name='price_cents',
            new_name='real_price_egyptian_cents',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='country',
            field=models.CharField(choices=[('Egypt', 'Egypt - £'), ('Qatar', 'Qatar - ﷼'), ('Bahrain', 'Bahrain - BD'), ('Saudi Arabia', 'Saudi Arabia ﷼'), ('United Arab Emirates', 'United Arab Emiartes د.إ'), ('Jordan', 'Jordan Dinar'), ('Kuwait', 'Kuwait ك'), ('Oman', 'Oman ﷼'), ('International', 'International $')], default='Egypt', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='display_float_price',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
    ]
