# Generated by Django 3.2.3 on 2021-10-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20211026_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='amount_cents_egypt',
            new_name='percent',
        ),
    ]
