# Generated by Django 3.2.3 on 2021-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_rename_amount_cents_egypt_promocode_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='promocode_price',
            field=models.FloatField(),
        ),
    ]
