# Generated by Django 3.2.3 on 2021-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20211026_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.CharField(default='International', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='promocode_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
