# Generated by Django 3.2.3 on 2021-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_membershiptype_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='number_of_students',
        ),
        migrations.AddField(
            model_name='membership',
            name='number_of_students',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
