# Generated by Django 3.2.3 on 2021-12-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20211222_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='std_display_float_price',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='std_real_price_egyptian_cents',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
