# Generated by Django 3.2.3 on 2021-12-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20211222_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='add_stds_price',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
