# Generated by Django 3.2.3 on 2021-10-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
