# Generated by Django 3.2.3 on 2021-09-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210820_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Text'), (1, 'Video'), (2, 'Quiz')]),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='course.lesson')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='course.topic')),
            ],
        ),
    ]
