# Generated by Django 3.2.3 on 2021-09-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210910_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='intro_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='course',
            name='intro_video_iframe',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_iframe',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
