# Generated by Django 3.2.3 on 2021-09-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210910_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='intro_video_iframe',
            field=models.FileField(upload_to=''),
        ),
    ]
