# Generated by Django 3.2.3 on 2021-09-11 10:28

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_intro_video_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_iframe',
            field=models.FileField(storage=course.models.APIVideoStorage(), upload_to=''),
        ),
    ]
