# Generated by Django 3.2.3 on 2021-09-11 10:32

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_video_video_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='', storage=course.models.APIVideoStorage(), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_iframe',
            field=models.TextField(),
        ),
    ]
