# Generated by Django 3.2.3 on 2021-09-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210911_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_iframe',
        ),
    ]
