# Generated by Django 3.2.3 on 2021-09-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210911_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='course.topic'),
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.topic'),
        ),
    ]
