# Generated by Django 3.2.3 on 2021-09-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20210913_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Text'), (1, 'Game'), (2, 'Video'), (3, 'Quiz')]),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('iframe', models.TextField()),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='course.lesson')),
                ('topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='course.topic')),
            ],
        ),
    ]
