# Generated by Django 3.2.3 on 2021-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20210923_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='track_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
