# Generated by Django 3.2.3 on 2021-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_toolbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
