# Generated by Django 3.2.3 on 2021-10-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
