# Generated by Django 3.2.3 on 2021-12-22 20:38

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_is_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(default='test.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='intro_video_iframe',
            field=models.FileField(blank=True, max_length=1000, null=True, storage=course.models.APIVideoStorage(), upload_to=''),
        ),
    ]
