# Generated by Django 3.2.3 on 2022-01-05 23:14

import course.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20211222_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='intro_video_iframe_ar',
            field=models.FileField(blank=True, max_length=1000, null=True, storage=course.models.APIVideoStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='iframe_ar',
            field=models.TextField(default='اختبار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='title_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary_ar',
            field=models.TextField(default='اختبار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqquiz',
            name='correct_choice_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqquiz',
            name='diagram_ar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mcqquiz',
            name='question_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcqquiz',
            name='wrong_choices_ar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=['اختبار', 'اختبار'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='text_ar',
            field=models.TextField(default='اختبار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='title_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfquiz',
            name='diagram_ar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tfquiz',
            name='question_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='title_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title_ar',
            field=models.CharField(default='اختبار', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_iframe_ar',
            field=models.FileField(default='اختبار', max_length=1000, storage=course.models.APIVideoStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
