# Generated by Django 3.2.3 on 2021-10-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_course_track_order'),
        ('toolbox', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbox',
            name='courses',
            field=models.ManyToManyField(related_name='toolbox', to='course.Course'),
        ),
    ]
