# Generated by Django 3.2.3 on 2021-10-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_alter_toolbox_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolbox',
            name='courses',
        ),
    ]
