# Generated by Django 3.2.3 on 2021-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0004_remove_toolbox_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='price_cents',
            field=models.IntegerField(default=120522),
            preserve_default=False,
        ),
    ]
