# Generated by Django 3.2.3 on 2021-10-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20211007_1916'),
        ('help_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='courses',
            field=models.ManyToManyField(related_name='periods', to='course.Course'),
        ),
    ]
