# Generated by Django 3.2.3 on 2021-10-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_sessions', '0002_auto_20211009_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpsession',
            old_name='title',
            new_name='help_text',
        ),
    ]
