# Generated by Django 3.2.3 on 2021-09-11 10:55

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_video_video_iframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_iframe',
        ),
        migrations.AlterField(
            model_name='course',
            name='intro_video_iframe',
            field=models.FileField(storage=course.models.APIVideoStorage(), upload_to=''),
        ),
    ]
