# Generated by Django 3.2.3 on 2021-09-11 11:01

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20210911_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='intro_video_iframe',
            field=models.FileField(max_length=1000, storage=course.models.APIVideoStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_iframe',
            field=models.FileField(max_length=1000, storage=course.models.APIVideoStorage(), upload_to=''),
        ),
    ]
